#!/bin/bash

# Armazenando argumentos em variáveis
read oldrev newrev ref

# Armazenando caminho do código fonte em variável
worktree=/var/www/deploy-automatico

echo "Atualizando código fonte"
git --work-tree="$worktree" checkout -f

if git --work-tree="$worktree" diff --name-only $oldrev $newrev | grep "^composer\.json$" -q; then
    echo "Atualizando bibliotecas"
    composer --working-dir=$worktree update --no-interaction
fi