#!/bin/bash

# Armazenando argumentos em variáveis
read oldrev newrev ref

# Armazenando caminho do código fonte em variável
worktree=/var/www/deploy-automatico

# Atualizando código fonte
git --work-tree="$worktree" checkout -f

if git --work-tree="$worktree" diff --name-only $oldrev $newrev | grep "^index\.html$" -q; then
    echo "Arquivo index.html alterado"
fi