#!/bin/bash

# Armazenando argumentos em variáveis
read oldrev newrev ref

# Armazenando caminho do código fonte em variável
worktree=/var/www/deploy-automatico

echo "Atualizando código fonte"
git --work-tree="$worktree" checkout -f

if git --work-tree="$worktree" diff --name-only $oldrev $newrev | grep "^public\/assets\/.*\?\.js$" -q; then
    echo "Refazendo build da aplicação"
    gulp build --cwd "$worktree"
fi