#!/bin/bash

# Armazenando argumentos em variáveis
read oldrev newrev ref

# Armazenando caminho do código fonte em variável
worktree=/var/www/deploy-automatico

echo "Iniciando modo de manutenção"
php $worktree/artisan down

echo "Atualizando código fonte"
git --work-tree="$worktree" checkout -f

echo "Rodando migrations";
php $worktree/artisan migrate --force

echo "Finalizando modo de manutenção"
php $worktree/artisan up